name: QuartzDefenders
version: 3.2
main: ua.endertainment.quartzdefenders.QuartzDefenders
api-version: 1.19
commands:
  quartzdefenders:
    usage: /<command> help
    aliases: [qd, quartz, qdef]
  team:
    usage: /<command> help
  stats:
    usage: /<command> help 
  gamebroadcast:
    usage: /<command> <message>
    aliases: [bc, gbc, gamebc, bcast]
  game:
    usage: /<command> help
  kit:
    usage: /<command> help