single_server_mode:
  enable: false
  
Lobby:
  lobby_world_name: world
  disable_damage: true
  infinity_food: true
  spawn:
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
blocked_commands:
  - "me"
  - "tell"
  - "w" 
  - "msg"
#There's no warranty to this thing to work correctly, use at own risk
blocked_enchants: []
    
database:
    use_mysql: false
    table_prefix: quartzdefenders
    host: localhost
    port: 3306
    database: database
    username: user
    password: password